-- 효돌이 PostgreSQL 스키마 (RDS). `schema.sql`(SQLite)과 쌍을 이룬다.
--
-- 두 파일을 하나로 합치지 않는 이유: PRAGMA / AUTOINCREMENT 는 SQLite 전용이고
-- IDENTITY 는 PostgreSQL 전용이라 한 파일로는 양쪽에서 돌릴 수 없다.
-- **한쪽을 고치면 반드시 다른 쪽도 고칠 것.**
--
-- 두 스키마가 반드시 맞춰야 하는 두 가지 (`db/index.js` 주석 참고):
--  * id 는 BIGINT 가 아니라 INTEGER 다. BIGINT 면 node-pg 가 문자열을 돌려줘
--    `nextCursor` 와 `alert.id` 가 문자열이 되고 프론트 비교가 어긋난다.
--  * boolean 자리는 BOOLEAN 이 아니라 정수 0/1 이다. node:sqlite 는 true/false
--    바인딩을 거부하므로, 두 드라이버가 같은 SQL 을 쓰려면 정수여야 한다.
--
-- 모든 시각은 ISO8601 UTC 문자열(TEXT)이다. timestamptz 로 바꾸지 말 것 —
-- 리포지토리와 프론트가 전부 문자열 비교/정렬을 전제한다.

-- 어르신 ↔ 로봇 ↔ 보호자 대화 로그
CREATE TABLE IF NOT EXISTS messages (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts        TEXT    NOT NULL,
  sender    TEXT    NOT NULL CHECK (sender IN ('senior', 'robot', 'guardian')),
  text      TEXT    NOT NULL,
  emotion   TEXT,
  -- 이 응답이 실제 Gemini에서 왔는지 mock 폴백인지. 예전엔 구분이 불가능해
  -- 실API 실패를 아무도 눈치채지 못했다.
  source    TEXT    CHECK (source IS NULL OR source IN ('gemini', 'mock', 'remote', 'legacy'))
);
CREATE INDEX IF NOT EXISTS idx_messages_ts ON messages (ts DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages (sender, id DESC);

-- 응급 알림
CREATE TABLE IF NOT EXISTS alerts (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts           TEXT    NOT NULL,
  type         TEXT    NOT NULL,   -- fall_detected | voice_trigger | manual_panic_button | vision_anomaly | no_motion | medication_missed
  severity     TEXT    NOT NULL DEFAULT 'critical' CHECK (severity IN ('critical', 'warning', 'info')),
  description  TEXT,
  confidence   DOUBLE PRECISION,   -- 감지기 신뢰도 0~1 (수동 버튼은 NULL)
  -- 스냅샷은 파일/S3에 저장하고 경로만 담는다.
  snapshot_path TEXT,
  resolved     INTEGER NOT NULL DEFAULT 0,
  resolved_at  TEXT,
  resolved_by  TEXT CHECK (resolved_by IS NULL OR resolved_by IN ('senior', 'guardian', 'auto'))
);
CREATE INDEX IF NOT EXISTS idx_alerts_unresolved ON alerts (resolved, ts DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_type_ts ON alerts (type, ts DESC);

-- 보호자/시스템 → 로봇 명령 큐
CREATE TABLE IF NOT EXISTS outbound_commands (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts           TEXT    NOT NULL,
  kind         TEXT    NOT NULL CHECK (kind IN ('speak', 'move', 'ping')),
  payload      TEXT    NOT NULL,   -- JSON 문자열
  -- 조회(pending)와 소비(ack)를 분리한다. 조회만으로 큐에서 사라지지 않는다.
  delivered    INTEGER NOT NULL DEFAULT 0,
  delivered_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_commands_pending ON outbound_commands (delivered, id);

-- 로봇 상태 (단일 행)
CREATE TABLE IF NOT EXISTS robot_status (
  id                INTEGER PRIMARY KEY CHECK (id = 1),
  status            TEXT    NOT NULL DEFAULT 'online',
  battery           INTEGER NOT NULL DEFAULT 100,
  last_active       TEXT    NOT NULL,
  senior_expression TEXT    NOT NULL DEFAULT 'neutral',
  is_emergency      INTEGER NOT NULL DEFAULT 0
);

-- 보호자 기기 Web Push 구독
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint   TEXT NOT NULL UNIQUE,
  keys_json  TEXT NOT NULL,
  label      TEXT,
  created_at TEXT NOT NULL
);

-- 감지기 원본 이벤트 (임계값 미만이라 알림이 되지 않은 것도 남긴다 — 임계값 튜닝 근거)
CREATE TABLE IF NOT EXISTS detections (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts          TEXT NOT NULL,
  source      TEXT NOT NULL,   -- fall_yolov8 | vision_gemini | mock
  type        TEXT NOT NULL,   -- fall | no_motion | abnormal_posture
  confidence  DOUBLE PRECISION NOT NULL,
  meta_json   TEXT,
  alert_id    INTEGER REFERENCES alerts (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_detections_ts ON detections (ts DESC);

-- 복약 일정. 한 행 = 한 번의 복용.
CREATE TABLE IF NOT EXISTS medications (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medicine_name TEXT    NOT NULL,
  scheduled_at  TEXT    NOT NULL,   -- ISO8601 UTC
  status        TEXT    NOT NULL DEFAULT 'scheduled'
                CHECK (status IN ('scheduled', 'taken', 'missed')),
  taken_at      TEXT,
  taken_by      TEXT CHECK (taken_by IS NULL OR taken_by IN ('senior', 'guardian')),
  -- 로봇이 실제로 소리 내어 알린 시각. 같은 약을 반복해서 말하지 않게 하는 가드다.
  reminded_at   TEXT,
  notes         TEXT,
  created_at    TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_medications_due ON medications (status, scheduled_at);
